### ISSUE TITLE
LInhome get token device

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linhome-android#10]
Good day!
Problem getting token in LINHOME app. I am using SIP connection through my Asterisk server. But after registering in the contact header, I do not receive the application token. I looked at your other application: LINPHONE it has the "Allow push notification" setting when it is turned on, the token appears, but I do not see it in the LINHOME application for the intercom. What can be done with these.

**Comment by arm-computech** [comment]
And your linhome-android application is still being developed, its support, since how can I not get an answer for this product?

**Comment by alex-eri** [comment]
duplicates #9
