### ISSUE TITLE
Direction of development, to obtain an application token?

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linhome-android#11]
The product is very good for organizing intercom. What I personally liked was the initial video stream, and the beautiful interface. But there is one thing, push notifications need to be improved, since they do not work at the moment. I use my personal Asterisk server, and I can't get the device token to send a notification. It would be great if you could organize a token receiving switch for Asterisk in the settings. To send through our server. And so the product is damp, that is, without this option I see no potential. I wanted to know if there are any plans to develop in this direction? Since it is precisely because of this moment that it is not possible to implement the intercom application itself.

**Comment by cdeschambc** [comment]
Hello, 
sorry for the late reply. 
The product is active and supported :).

To answer your question the application send their push token in conformance to this RFC : https://datatracker.ietf.org/doc/html/rfc8599 . You can use flexisip push gateway in conjunction with SIP proxy dependencies on the app so app will register to your asterisk with an contact beeing on the flexisip push gateway, and the push gateway will handle automatically the sending of push.

**Comment by arm-computech** [comment]
No, that's just the point, I'm interested in SIP registration on my Asterisk server.
Do you plan to transfer this application token to a third-party Asterisk server, as it is implemented in the Linphone product. Since at the moment, due to the impossibility of sending push notifications from our server, the product makes little sense. Since, even the logical implementation should be exactly the same for intercom systems.

**Comment by arm-computech** [comment]
And I would like to draw your attention to the broken link linhome-shared-themes @ cb385c5. Error 404, in your repository

**Comment by cdeschambc** [comment]
A pushgateway will be completely transparent to you and asterisk. Your apps will register to your asterisk and the pushgateway in parrallel (automatically, you have nothing to do). The contact address will just be different to the asterisk, instead of the IP of the app it will be a URI on the Pushgateway, which wil relay the invite in a push form. 

Most of the intercom vendors who use Linphone products do so. You can get in touch with Belledonnes Communications sales rep to get further info on the architecture.

For the repo note this is just a clone, our master repo is here : https://gitlab.linphone.org/BC/public/linhome-android
the broken link is just the submodule (git submodule update --init --recursive). 
regards

**Comment by arm-computech** [comment]
How, then, can Asterisk organize the sending of invitations for push notifications to your Asterisk? Because with the standard behavior, nothing happens.

**Comment by cdeschambc** [comment]
If you use the Linhome android app that is on store now, and choose the option of use a SIP account, and in SIP account enter the details of you asterisk the Push account will be created automatically on our server, and the app will register to your asterisk with a URL that points to the push account created (you can confirm so by looking into your asterisk registration DB).

**Comment by arm-computech** [comment]
Not all of this is available, but Push notifications do not work.

**Comment by alex-eri** [comment]
@cdeschambc hello. Why not to send push tokens and contact with https(or something like it, maybe sip inform) just after register? Then asterisk users can just send you contact via http before Dial. I not working with @arm-computech , but my project owner want  to not route call to side servers.

**Comment by cdeschambc** [comment]
Hello, 
The solution aims to follow as much as possible the RFCs specifications. The one for push token update to server is described here. 
But nothing prevent you from parsing this contact line and extract the push token to later send push using the token. 
You can find the syntax to do so inside the rfc itself. 
https://datatracker.ietf.org/doc/html/rfc8599
