### ISSUE TITLE
403 Domain forbidden from sip.linhome.org

### ISSUE THREAD

**Issue by alex-eri** [BelledonneCommunications/linhome-android#12]
Then  linhome android call intercom via asterisk - it call directly asterisk.

After answer asterisk sends invite to sip:3l4t8pyg5wj-@sip.linhome.org contact

sip.linhome.org answers `403 Domain forbidden`  so INVITE (SDP) not reached intercom.

So I have one way audio.

**Comment by presneryurii** [comment]
Hello, the problem is still not solved?

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome.
This might have happened during our server upgrade process. 
If you still encounter the issue and need a fix can you please kindly test with latest 1.3 and reopen the issue if applicable
kind regards
