### ISSUE TITLE
Define ringtone + volume incoming call is verry low

### ISSUE THREAD

**Issue by pergolafabio** [BelledonneCommunications/linhome-android#18]
Hi, when I receive a call, the notification ringtone volume is extremely low?? Also is there a setting to define a custom ringtone?

Thx

**Comment by leonardocompagnoni** [comment]
Ciao Fabio, 
Ho visto che hai chiuso la issues, per caso hai trovato il modo di cambiare suoneria? Ho anche io lo stesso problema. Grazie

**Comment by pergolafabio** [comment]
No, stopped using it
