### ISSUE TITLE
Vibrate only for incoming

### ISSUE THREAD

**Issue by a-march** [BelledonneCommunications/linhome-android#2]
When there is an incoming call, there is only a vibration call, there is no call.

**Comment by Viish** [comment]
Please be more explicit and provide logs.

**Comment by a-march** [comment]
https://www.linphone.org:444//tmp/6075ea1601897_f99c85f87cb817c33593.gz

**Comment by a-march** [comment]
The application works with the Dahua panel VTO6531H via FreePBX. When you receive a call, you receive a notification and the smartphone vibrates, but there is no ringtone (melody). Android has all the permissions (including the call). But only a vibration call works.

**Comment by Viish** [comment]
Hi,

This is because you are doing early media, thus we don't play the ringtone.
You can change that by calling `linphone_core_set_ring_during_incoming_early_media()` or set the following in the factory config file:
```
[sound]
ring_during_incoming_early_media=1
```

Cheers,

**Comment by Viish** [comment]
Actually I found an issue in how we handled ringing during early-media in our SDK for Android and I fixed it.
Using SDK 5.0.0-alpha-26 or newer should fix the issue.

**Comment by a-march** [comment]
Where to get apk? 


14 апреля 2021, 12:51:13, от "Sylvain Berfini" < ***@***.*** >:



Actually I found an issue in how we handled ringing during early-media in our SDK for Android and I fixed it.
Using SDK 5.0.0-alpha-26 or newer should fix the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



--
С Уважением, Марченко Александр.
***@***.***
(048)799-00-70
067-951-24-88
www.remcom.odessa.ua

**Comment by Viish** [comment]
To have a linhome APK with the latest SDK you will have to build it yourself.

**Comment by a-march** [comment]
Do you plan to post it on the play market?

14 апреля 2021, 14:09:27, от "Sylvain Berfini" < ***@***.*** >:



To have a linhome APK with the latest SDK you will have to build it yourself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



--
С Уважением, Марченко Александр.
***@***.***
(048)799-00-70
067-951-24-88
www.remcom.odessa.ua

**Comment by Viish** [comment]
> Do you plan to post it on the play market?

No, we don't have a new released scheduled yet.

**Comment by a-march** [comment]
How do I get SDK 5.0.0-alpha-26 or newer?

14 апреля 2021, 17:05:40, от "Sylvain Berfini" ***@***.***>:


Do you plan to post it on the play market?
No, we don't have a new released scheduled yet.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


--
С Уважением, Марченко Александр.
***@***.***
(048)799-00-70
067-951-24-88
www.remcom.odessa.ua

**Comment by Viish** [comment]
> How do I get SDK 5.0.0-alpha-26 or newer?

It's available on our maven repository: https://linphone.org/maven_repository/org/linphone/linphone-sdk-android/5.0.0-alpha.27+3d8dd4a/

**Comment by a-march** [comment]
And take the source code for Linhome from here https://gitlab.linphone.org/BC/public/linhome-android  ?
