### ISSUE TITLE
Confusing: google-services.json is part of this project??

### ISSUE THREAD

**Issue by pergolafabio** [BelledonneCommunications/linhome-android#24]
Hi,

questions about push, its confuses me... in readme they mention that the google_services.json is not part of the project? that it has been added to igonore list, but if i clone this project, the file is just part of it? so is readme wrong?

Also, the included file, only works when we use  SIP extentions subscribed at https://subscribe.linhome.org/  , am i right? if we use our own PBX, then we need to setup flexisip too ?

Also, when making a debug package, do we need to change it also in the google_services file   "package_name": "org.linhome"  => org.linhome.debug? 

thnx for feedback

```
However to make Firebase push notifications work, the project needs to have a file named app/google-services.json that contains some confidential informations, so you won't find it (it has been added to the .gitignore file). This means that if you compile this project, you won't have push notification feature working in the app!

To enable them, just add your own google-services.json in the app folder.
```

**Comment by cdeschambc** [comment]
Hello, 
Yes our own google-services.json is present on the repo (and it should not be you are right) however it can't be used as server keys are required to be used on the other end to send notification. 
In fact what the doc should say is that google-services.json should be replaced by your own. 
In our Firebase project we have 2 package IDs defined org.linhome and org.linhome.debug depending on the build flavour used  (release or debug). 
You can do the same on your own project if you like this way you can configure your server to send notifications to both apps. 
regards

**Comment by pergolafabio** [comment]
Hi , thnx for feedback...

By "your server" , you mean our flexisip server? I don't have flexisip installed, maybe later in future... I'm using the free linhome sip service... Then I need to use the supplied JSON file, right?

If I setup my own flexisip, then I need to supply my own JSON...

Correct? :-(

**Comment by cdeschambc** [comment]
Hello, 
The Free Linhome SIP service is only intended to run with Linhome apps that run on stores, it's not really intended to connect custom made or locally built apps. 
If you need help for a custom solution please feel free to fill this form https://linphone.org/contact 
regards

**Comment by pergolafabio** [comment]
Ah, I wasn't aware of that...
But the JSON indeed works with free sip service, it's only for home use... 
I'm just modifying it to inject video as early media, that's a thing I miss in this nice linhome app...
Early media only works on 1 to 1 call, not if you call multiple users (group)... Haven't find a PBX that is capable of doing that
