### ISSUE TITLE
No pn-prid in register like linphone does...

### ISSUE THREAD

**Issue by pergolafabio** [BelledonneCommunications/linhome-android#26]
Hi, when push is enabled on linphone, it sends a pn-prid token in the registrar header
But push is already enabled in Linhome, but i dont see any pn-prid coming in

I'm using my own json file, and was ablle to retrieve the token  this way  below ...

But why doesnt linhome send it to asterisk like Linphone does? do we need to enable it somewhere?

thnx

```
FirebaseMessaging.getInstance().token.addOnCompleteListener(OnCompleteListener { task ->
    if (!task.isSuccessful) {
        Log.w(TAG, "Fetching FCM registration token failed", task.exception)
        return@OnCompleteListener
    }

    // Get new FCM registration token
    val token = task.result
```

**Comment by savan15** [comment]
@pergolafabio 
Have you resolved this issue?

Could you please tell me how you resolved it? I’m facing the same problem as well.

**Comment by pergolafabio** [comment]
I stopped using it ...

**Comment by savan15** [comment]
@pergolafabio 
Thanks for your quick answer.

Does anyone has resolve this issue?

**Comment by cdescham** [comment]
Hello @savan15 
This Linhome has been designed to work on store in the following way : 
- If the app uses a Linhome account it sends the push parameters to the server
- if the app uses a regular SIP account it does not send  the push parameter but instead creates a so called push account onto Linhome server that will act as a push gateway. Push parameters are sent to this account. 
This scenario is designed for app registering directly to video door bell which do not support push sending.

But of course you can change this behaviour inside code for building your own app. 
kind regards

**Comment by savan15** [comment]
@cdescham 
Thank you for your valuable feedback and for clarifying my doubt.
