### ISSUE TITLE
No access to submodule git@github.com:BelledonneCommunications/linhome-shared-themes

### ISSUE THREAD

**Issue by mixaz** [BelledonneCommunications/linhome-android#27]
```[gmixaz@arch-i7 linhome-android]$ git submodule update --init --recursive
Submodule 'linhome-shared-themes' (git@github.com:BelledonneCommunications/linhome-shared-themes) registered for path 'linhome-shared-themes'
Cloning into '/home/gmixaz/linhome-android/linhome-shared-themes'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:BelledonneCommunications/linhome-shared-themes' into submodule path '/home/gmixaz/linhome-android/linhome-shared-themes' failed
```

**Comment by cdeschambc** [comment]
Hello, 
We are using gitlab as main, it seems like the cloning on GitHub has issues. 
You can clone directly from gitlab using : https://gitlab.linphone.org/BC/public/linhome-android 
regards

**Comment by mixaz** [comment]
@cdeschambc Thanks, I confirm - building from gitlab repo works OK

**Comment by mixaz** [comment]
Is https://github.com/BelledonneCommunications/linhome-android repo a valid one (latest source code), can I fork it or shall I fork from the gitlab one?

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response.
We have recorded this issue internally and will setup synchronization the gitlab repository of shared themes with the github one.
As suggested you can use the gitlab one for now. 
regards

**Comment by cdeschambc** [comment]
internal issue https://linphone.atlassian.net/browse/DEVOPS-165

**Comment by KyronNextLevel** [comment]
The issue is fixed. Thank you for pointing it out.
