### ISSUE TITLE
No incoming sound

### ISSUE THREAD

**Issue by andreapier** [BelledonneCommunications/linhome-android#3]
Hello,
I just installed linhome for android and configured it. I think it is a great app, but unfortunately incoming audio is not working.  
Specifically, this is what is happening:
 - If I receive a call, I cannot hear the caller
 - If I start a call to the doorbell, I cannot hear the person at the doorbell
 - The app also doesn't ring when receiving a call
 - Everything else, including video, outgoing audio and early-media works as expected  
  
I think it is an app issue as audio works fine when using linphone app.  
Please tell me if you need other info.  
Thanks

**Comment by cdeschambc** [comment]
Hello, 
Can you please send a log (from Settings menu) ?

**Comment by andreapier** [comment]
Sorry for late reply.
Please find my [log here](https://www.linphone.org:444//tmp/60811d6e23b9a_db0b5160d5e0160a46ae.gz).
In the mean time, I did some more tests and found out that:
- my device works fine if I plug headphones. I can hear the other hand and it rings when receiving call. Unfortunately this is a no go
- I tried with another device (my smartphone, Huawey P10) and everything works perfectly
  
It looks like something device-related.  
I am using a Samsung Galaxy Tab A (SM-T510) with cyanogenmod 17.1 (android 10).

Thanks

**Comment by cdeschambc** [comment]
Hello, 
thank you for the log. 
I believe it is just a matter of output device selection inside the app
I have pushed a commit that forces the audio to speaker on tablets : 
(https://gitlab.linphone.org/BC/public/linhome-android/-/commit/8ba54be252d25ec522730eb9cbc384f1f8f72225)
Can you please let me know if that fixes it on your device ? 
thank you in advance for your feedback.
Christophe

**Comment by cdeschambc** [comment]
ps : if you need an APK for testing you can find one from our CI : 
https://gitlab.linphone.org/BC/public/linhome-android/-/jobs/453312/artifacts/browse/app/build/outputs/apk/

**Comment by andreapier** [comment]
I only tried audio during call, but I can confirm **it works now**!!  
I will confirm I can also hear the tablet ringing later, I cannot try it now.  
Will let you know.
Thank you very much!

**Comment by andreapier** [comment]
I confirm it works just fine!  
There is only one (not so important) thing left, but maybe it could help to further improve your app.  
When I tried linhome in my smartphone I noticed the classic speaker icon. Tapping it would mute/unmute audio.  
Even with your latest commit my tablet doesn't show this icon. Could this be related to my original issue?
I will leave this issue open a little longer. If you feel like closing it, go ahead. Otherwise, I'll close it next week.
Again, thanks

**Comment by cdeschambc** [comment]
Thank you for your feedback. 
We intentionally chose to de the speaker button in tablets as we think the de-facto route should be the speaker for those. 
But you can re-add it very easily in your custom app it's just a couple places.

**Comment by andreapier** [comment]
Hi, do you think you can release a new app version? I'd prefer to stick to the official app installed through Play Store.

**Comment by cdeschambc** [comment]
Hello, 
We have an upcoming release coming in a few days with other updates. 
It will incorporate this fix.

**Comment by andreapier** [comment]
Hi, sorry to ask again but I'd like to know if next version will be released anytime soon. Otherwise I'll stick to your unofficial build.
Thanks

**Comment by cdescham** [comment]
Hello,
yes sorry we are waiting for some translations texts before releasing, but that should come shortly
regards
