### ISSUE TITLE
Action buttons don't show during video call

### ISSUE THREAD

**Issue by pgorod** [BelledonneCommunications/linhome-android#30]
Hi! I just discovered Linhome after making some feature requests for Linphone and getting sent here :-)

I am trying Linhome and I could easily get it to make video calls to my door video, a 2N Helios. I am using the sip.linhome.org account, and my door device is not registering to that account. This means I can only make calls from the door to the phone, not the other way around (which is fine with me, I just mention it in case it is relevant).

I set up also an "Action", to send the DTMF code **`7*`** which triggers the door lock to open.

But I can't see any way to tell Linhome to run the action. No button, nothing. I tried full-screen, normal view, I tapped everywhere on screen and nothing happened...

My action is set up like this:

![image](https://user-images.githubusercontent.com/15945027/213797947-f32cbaba-5d58-4500-ac99-fceafce5adcf.png)

## Technical info

Device: OnePlus Nord CE 5G
OS: Android 11
Version of the App: [5.0.5](https://www.youtube.com/watch?v=iV5VKdcQOJE)
Version of the SDK: 5.2.15
Where you did got it from: Play Store
Oxygen OS 11.0.5

Am I doing something wrong?
Thanks!

**Comment by cdeschambc** [comment]
Hello, 
Actions button will show automatically when the app matches the calling device SIP Uri (from the from Address of the caller) to the SIP address of a device defined in the application. 
From your screen shot I can see the domain name of the device is sip.linhome.org, so it is unlikely your device will have such a domain name when calling the app.

**Comment by pgorod** [comment]
Thanks for your reply! I am not sure I understand the logic behind that behaviour, if it is by design. 

I can configure my doorbell to initiate a SIP call, and I can only tell it to dial to "sip:myname@linhome.org". I don't think it sends any other information, or at least I can't configure it.

So how am I supposed to get Linhome to match?

Thanks for your help!

**Comment by pgorod** [comment]
Ok, so I was able to get the invite in the log:

```
SIP/2.0 487 Request terminated
Via: SIP/2.0/TLS sip8.linphone.org;received=2001:41d0:403:2767::1234;rport;branch=z9hG4bK.Z6F0j3QF5DvNSvg4gt9c5SrDpg
Via: SIP/2.0/UDP 10.0.0.121:5060;received=81.193.70.25;rport=1024;branch=z9hG4bK68074671
From: "Porta Abrir:7*" <sip:300@10.0.0.10:5060>;tag=469118163
To: <sip:mylinhomeaccountname@sip.linhome.org>;tag=Een1hB9
Call-ID: 1543195590
CSeq: 20 INVITE
User-Agent: Linhome/5.0.0 LinphoneSDK/4.5.0 (tags/4.5.0^0)
Supported: replaces, outbound, gruu
Content-Length: 0
```

And it's true, my "History" always shows "unrecognized device".

I guess I was mis-understanding what the "sip address" field in the Device configuration was. I was also not thinking of Linhome as a "multi-device" app...

After changing the device's SIP address field to the "From" address being sent from the call initiator, Linhome was able to recognize the device, and I started seeing the button.

I think I will close this issue it is solved for me. Maybe some of these fields could be made clearer but I am not sure what to suggest, specifically. I'll leave that to you  :-)

Perhaps a nice idea for a feature would be in History, when it is an unrecognized device, have a button to save that unrecognized device, so that it is recognized next time. This would intuitively have led me in the right direction.

Thanks!

**Comment by cdeschambc** [comment]
Good suggestion, we've thought about it too, will pass it on to PM. FYI we are about to release a new version of the app with more features and bug fixes.

**Comment by pergolafabio** [comment]
looking forward to the new app release, will it include now the background mode?

**Comment by pergolafabio** [comment]
ah, nm, i see background mode was added  :-)

i was hoping to see an option to include RTSP stream manually where door intercoms are not able to send the video in early media
