### ISSUE TITLE
Feature request: enable / disable app easily

### ISSUE THREAD

**Issue by pgorod** [BelledonneCommunications/linhome-android#31]
Hi

Often we need to turn the app off in order not to get annoyed by devices ringing. For example, for me it's when I leave the office, I am not supposed to answer the video door, other people who are there can take care of that. So I might need to switch on and off several times a day.

In Linphone I do this with **Account settings, disable**, but I wish it required less taps. It is a very frequent operation.

In Linhome there is no way to manage this except unlinking the account, and then having to reconfigure everything afterwards?

Eventually this request could extend to per-device enable/disable controls. I guess a small checkbox on the device list could let me "subscribe" to individual devices.

Thanks

**Comment by cdeschambc** [comment]
Thanks for your suggestion which totally makes sense, I'll pass it on to product management

**Comment by pgorod** [comment]
Cool. Just a question: since this is a deal-breaker for us (we can't use the app like this), do you know of any Android trick that might work for me as a workaround? Just some way to keep Linhome from ringing when I don't want it.

I have tried "Freezing" the app with Titanium Backup, and it sort of works; I mean, it keeps Linhome from running, but it also deletes the icon from my Home screen, then I have to add it again every time I re-enable the app. If I had a simpler way of blocking Linhome temporarily, that I could automate, that would be great.

Say, using Tasker to move some configuration file to a different directory temporarily? Any advanced user "hack" would be fine with me. Thanks in advance.

**Comment by cdeschambc** [comment]
In your version of you app disabling notifications for Linhome and killing it should do the job as it is what wakes it up.

**Comment by pgorod** [comment]
For now, I will use an app called Ice Box to freeze/unfreeze Linhome as necessary.

But it's not very user-friendly, I will have to wait until the feature is added to Linhome before I can migrate the rest of the people using this system (from Linphone to Linhome).

Thanks for your assistance!

**Comment by JonathanBartet** [comment]
Hi @pgorod,

Thanks for your feedback. 
Disabling notifications by devices is too specific to include it in our roadmap.
You can buy a specific development for your company if it's essential for you.

Thank you again for your issue.
Regards,

**Comment by pgorod** [comment]
Hi, the only thing that is essential to us is a generic enable/disable. The other suggestion (per-device setting) was just an idea. Thanks

**Comment by pgorod** [comment]
Hi, any news on this? 

It's a pity that this app fills all the requirements for my needs except a simple on/off switch... I have my workarounds but they're too hacky for regular users.

Any timeline on when a new release could be imminent?

Thanks in advance!

**Comment by pgorod** [comment]
I see Linphone gets new versions every once in a while, but Linhome is stalled... please, please release a new version with a simple check-box to disable the app when we don't want to take calls. It's such a simple thing that would make a total difference for the usability of this app. I've been waiting for months to deploy this to a group of people just because of this.

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome.
Since this ticket is related to a feature development please contact the sales team through this online form : https://www.linhome.org/contact/ 
kind regards
