### ISSUE TITLE
Use a Linhome account doesn't work

### ISSUE THREAD

**Issue by pgorod** [BelledonneCommunications/linhome-android#34]
Hi! When adding an account, this doesn't work:

1. Go to account assistant
2. Select **Use a Linhome account**
3. Enter user name (e.g. `myuser`) and password (e.g. `mypass`).
4. See an error: `Unknown username or incorrect password`

But those credentials work just fine to log in at **https://subscribe.linhome.org/login** !

And I can also login in Linhome app by doing this instead:

1. Go to account assistant
2. Select **Use your SIP account**
3. Enter user name (e.g. `myuser`), SIP domain (`sip.linhome.org`, I wish this value was there by default so I wouldn't have to type it every time) and password (e.g. `mypass`).
4. It works

Am I missing something, or is this a bug? Thanks

_Tested on version 1.2 beta_

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response.
I tried to reproduce the issue just now, but I was able to login using 1.3 from store. 
closing this issue, please kindly reopen attaching a log file if you are still experiencing it. 
kind regards
