### ISSUE TITLE
User experience in Call Screen

### ISSUE THREAD

**Issue by pgorod** [BelledonneCommunications/linhome-android#37]
When I answer a call from my video door-phone (a recognized device I configured), I get a screen like this:

<img src="https://github.com/BelledonneCommunications/linhome-android/assets/15945027/e5394833-4998-4aa0-8f59-cb1a5b7ca34c" width=20% height=20%>

Note the absence of the status bar on top and the navigation bar (or whatever it is called) at the bottom. Here is a screenshot of the normal app screen so you can see how my phone looks, regarding the top and bottom toolbars:

<img src="https://github.com/BelledonneCommunications/linhome-android/assets/15945027/184d060a-b064-41d7-8aff-7aaf8b488751" width=20% height=20%>

If I touch anything, the Linhome buttons also disappear (`Open the door`, `Mute`, `Hang up`, `Turn on` ), and now it looks like this:

<img src="https://github.com/BelledonneCommunications/linhome-android/assets/15945027/505ed2e8-ba9d-4e54-a826-d3630b8c740a" width=20% height=20%>

I _think_ the logic behind all this hiding screen elements is that video screens are, for some reason, meant to be "immersive", so that I can dive into some episode of a series I am watching, etc.

**None of that is a good idea for a door entry device app. Just leave everything visible on screen, please.**

I want the `Open the door` button to stick right there, not that it disappears just because I made some accidental tap. 

I want to be able to check my top status bar, for wi-fi connectivity ("why is my image so laggy?..."), the time of day ("John is arriving early..."), etc.

I want to be able to use my bottom navigation toolbar! I might want to switch apps to check some information while I am talking to the parcel delivery guy, or to send quickly a WhatsApp to somebody who is at home, but not answering the door, while I am remotely answering it.

I also have that fourth button on the right of my bottom toolbar which is important to me: it's the **Accessibility** feature called "Magnification shortcut". It helps people with poor eye-sight zoom in on parts of the screen. It's quite helpful while answering the door so I can quickly zoom in on the face until I recognize the person.

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome and very constructive feedback.
Since this ticket is related to a feature development please contact the sales team through this online form : https://www.linhome.org/contact/ 
kind regards

**Comment by julien-fb** [comment]
Hello,
As mentioned in my mail, we are having a 1.4 version of Linhome on our roadmap. This version will include improvements coming from comments and feedback from users of the application and we thank you for that. 
Please also note that our business model is not different from other companies in the open source world. Features are paid by clients requesting for them, at a reduced costs, as they will beneficiate the entire community. 
We are not targeting end users of the Linhome application  hence the lack of any commercial offer adapted to individuals.
However, we are leaving it accessible for anyone who wants to use it for free, as you stated.
Kind regards,

**Comment by pgorod** [comment]
> Features are paid by clients requesting for them, at a reduced costs, as they will beneficiate the entire community.

Ok, so is there a reasonable price tag that you can give me? For example, a simple feature such [as checkbox to enable or disable the app](https://github.com/BelledonneCommunications/linhome-android/issues/31).
