### ISSUE TITLE
Linhome android, running the application in the background

### ISSUE THREAD

**Issue by a-march** [BelledonneCommunications/linhome-android#4]
Good day! Thank you for your work! After the update on April 19, the application rings normally with an incoming call. However, the application stopped working after restarting the device (autorun is enabled), and after clearing the gadget's memory (all background permissions in android are also set).

**Comment by cdeschambc** [comment]
Hello, 
This version of the app does not have background mode enabled. 
it relies upon push notifications to restart upon an incoming call. 
did you make your tests using the store app ? is it connected to the internet ?

**Comment by a-march** [comment]
Good day! yes, I took the application here https://play.google.com/store/apps/details?id=org.linhome Internet is there Linphone is working.

**Comment by cdeschambc** [comment]
Hi, 
Background mode activation is planned for the next release. 
This version should wake up the app through notification though. 
Can you please send a log of the app (from settings menu) after starting it so we can check it registers properly to push notifications ? 
Thank you

**Comment by a-march** [comment]
https://www.linphone.org:444//tmp/6086f5cb3dc00_3f5e308c19ebc34cfd27.gz

**Comment by cdeschambc** [comment]
Good day! and thanks for the log file. 
I see your app registers properly to Linhome server with a push enabled account automatically created.
REGISTER sip:sip.linhome.org SIP/2.0
[..]
Contact: <sip:i0nl27tcqaf-@192.168.1.177:46855;pn-type=firebase;app-id=1041242817246;pn-tok=fZY4-4paTKmNmE3Yc_SIye:APA91bGl3dPS30HJWstnuRV4pKVxSsDyE_6hGU4cYrzwFcvmG4orjZ6pjoYRpTyMqFCzGkfkPo32ozI2L1qMdQHl99XcKuDOUH8Xh5rzhbc-pcdDKNCL3d3V4gDIqlB7EQX0AqWNPxTs;pn-timeout=0;pn-silent=1;transport=tls>;+sip.instance="<urn:uuid:2766b3a9-3ee6-00ff-a401-155c355af257>"


I see your app registers properly to your Asterisk using as a contact the push gateway account 
REGISTER sip:85.238.102.20 SIP/2.0
[..]
Contact: <sip:i0nl27tcqaf-@sip.linhome.org;gr=urn:uuid:2766b3a9-3ee6-00ff-a401-155c355af257>

But I don't see traces of a push notification incoming. 
Can you please double check on the asterisk that the invite get sent to the following address : 
sip:i0nl27tcqaf-@sip.linhome.org

and provide us with a Call-Id so we can track it up on Linhome server ? 

thanks in advance

**Comment by a-march** [comment]
Good day!
https://www.linphone.org:444//tmp/6087c82b041ab_a878f942640624a564c0.gz
sip linhome: 10005@85.238.102.20
sip VTO: 10002@85.238.102.20
I beg your pardon, I do not understand very well.

**Comment by cdeschambc** [comment]
When your VTO call Linhome app it should send SIP invite to sip:i0nl27tcqaf-@sip.linhome.org (this is automatic as when Linhome registered to 85.238.102.20 it used sip:i0nl27tcqaf-@sip.linhome.org as a contact address). 
so my question is can you look into the logs of 85.238.102.20 for the call from VTO to Linhome to see that 85.238.102.20 is sending the INVITE to sip:i0nl27tcqaf-@sip.linhome.org,  and if yes  provide me with a call-ID for such a call (10002->10005) ?

**Comment by arm-computech** [comment]
I am trying to organize Push notifications for a SIP account. I can not understand how you can get pn-tok to Asterisk when registering a SIP and how to send PUSH notifications.
I also wanted to know how it is possible to transfer pn-tok to an asterisk, in which files to register

**Comment by arm-computech** [comment]
In which file can I pass the token to Asterisk?

**Comment by alex-eri** [comment]
@cdeschambc  linhome-android send two contacts to server. Asterisk usually dial only one of them because of legacy dialplan. This issue i solved with `Dial(${PJSIP_DIAL_CONTACTS(${EXTEN})})`

but https://github.com/BelledonneCommunications/linphone-iphone/issues/774 breaks it

**Comment by cdeschambc** [comment]
linhome-android should only send one contact to your server and that is the <generated username by the app>@sip.linhome.org so when someone calls your extension on asterisk, asterisk should pick this only contact URI and forward the invite to flexisip server (sip.linhome.org) which holds the contact details you showed above (that contains push parameter to wake up apps)
