### ISSUE TITLE
Linphone not working on Tablet Android 13

### ISSUE THREAD

**Issue by JumpCanDo** [BelledonneCommunications/linhome-android#40]
Hi, I am using a Dahua VTO door station as a sip server. It works perfectly fine with Linphone on the Android 13 Tablets.
However, I prefer the Linhome, because it got an action option with a code that is being sent to open a door or gate.
Linhome can be installed and devices added, but calls are not working work (it looks like it is calling, but it does not connect to the door station. And when calling another devices, it does not ring the device).
I installed linphone on a Samsung Phone (android 13 as well) in the same way and that works perfectly fine.

Any Sugggestion?

**Comment by cdeschambc** [comment]
Hello,
Apologies for the delayed response and thank you for your interest in Linhome.
If the issue is still accurate can you please kindly try again with latest 1.3 version of Linhome which has been upgraded to support later android versions.
kind regards

**Comment by JumpCanDo** [comment]
Hi Christophe,
I am using a Dahua SIP server that requires Sip user addresses that includes "#" (like 9901#1, 9901#2 etc.)
It does work in Linphone, but I prefer Linhome as does provide door opening functionality and function as intercom to the rooms and to the door station.
Could you please allow special characters for the Linhome app?

Thank you
Udo

**Comment by JumpCanDo** [comment]
Thank you.
