### ISSUE TITLE
Where "pn-tok"?

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linhome-android#7]
Good day!
I do not know where to write, please help.
Working on push notifications. But for push notifications you need to get pn-tok, but in asterisk I don't get it in Reg. Contact, that is, completely different information comes in.

In which file do you transfer data to the header for Asterisk?

**Comment by pergolafabio** [comment]
hey @arm-computech  , did you find it
if you enable push on linphone, i can see indeed an "pn-prid" token in the asterisk registrar
But seems Linhome doesnt send a pn-prid or pn-tok

So how is this handled with Linhome?

thnx

@Viish , maybe you can gives us some info about it?
i'm using my own json file

Or do i need to look for this one?
```
[net]
use_legacy_push_notification_params=1
```
