### ISSUE TITLE
Getting Application Token in Contact Header for Your Asterisk Server

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linhome-android#9]
Good day!
Problem getting app token. I use a SIP connection through my Asterisk server. But after registering in the contact header, I do not receive the application token. I looked at another application of yours: linphone it has a setting "Allow push notification" when it is turned on, a token appears, but in this application for an intercom, I do not see it.

**Comment by alex-eri** [comment]
This application uses sip-proxy and send tokens to proxy only.

**Comment by cdeschambc** [comment]
hello, 

Those functions are integrated in upcoming version of linphone-sdk which are not yet fit in Linhome.  
But for now you can customise your own app if you wish in order to do so.
